#!/usr/bin/env node
import { readFile, writeFile } from 'node:fs/promises';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const read = async (p) => JSON.parse(await readFile(join(ROOT, p), 'utf8'));

const catalog = await read('catalog.json');
const gatesDoc = await read('gates.json');
const active = gatesDoc.gates.filter((g) => !g.deprecated);
const deprecated = gatesDoc.gates.filter((g) => g.deprecated);

const byStage = new Map();
const byDimension = new Map();
for (const g of active) {
  byStage.set(g.stage, (byStage.get(g.stage) ?? 0) + 1);
  const d = byDimension.get(g.dimension) ?? { block: 0, warn: 0 };
  d[g.severity] += 1;
  byDimension.set(g.dimension, d);
}

const stageRows = Object.keys(gatesDoc.stages)
  .map((s) => `| \`${s}\` | ${byStage.get(s) ?? 0} | ${gatesDoc.stages[s]} |`)
  .join('\n');

const dimRows = catalog.dimensions
  .map((d) => {
    const c = byDimension.get(d.id) ?? { block: 0, warn: 0 };
    return `| [${d.id}](${d.path}) | ${d.status} | ${c.block} | ${c.warn} |`;
  })
  .join('\n');

const planned = (catalog.planned ?? [])
  .map((p) => `- \`${p.id}\` — ${p.summary}`)
  .join('\n');

const out = `# STATUS

> Generated by \`checks/render-status.mjs\`. Do not edit by hand — change \`catalog.json\` / \`gates.json\` / the dimension docs instead.

Standard version: \`${catalog.version}\`

Active gates: **${active.length}** · deprecated (kept, never reused): **${deprecated.length}**

## Gates by dimension

Counts exclude deprecated ids.

| Dimension | Status | block | warn |
|-----------|--------|-------|------|
${dimRows}
| **total** | — | **${active.filter((g) => g.severity === 'block').length}** | **${active.filter((g) => g.severity === 'warn').length}** |

## Gates by stage

| Stage | Gates | Meaning |
|-------|-------|---------|
${stageRows}

${planned ? `## Planned dimensions\n\n${planned}\n` : ''}
## How to use

- 引用门禁请用 id（例如 \`MOAT-1\`），不要引用行号或段落标题。
- 上线判定去 [ship-standard](https://github.com/miounet11/ship-standard)。
- 怎么写代码去 [build-standard](https://github.com/miounet11/build-standard)。
- 六面修交接本去 [ability-harness](https://github.com/miounet11/ability-harness)。
- 迭代 / 升级 / 修 bug 审查去 [review-harness](https://github.com/miounet11/review-harness)。
`;

await writeFile(join(ROOT, 'STATUS.md'), out);
console.log(`wrote STATUS.md (${active.length} active / ${deprecated.length} deprecated, version ${catalog.version})`);
